import{initializeApp}from"https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,sendPasswordResetEmail}from"https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";
import{getFirestore,collection,addDoc,setDoc,doc,getDoc,getDocs,updateDoc,deleteDoc,query,orderBy,limit,onSnapshot,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyDA0csj0AOrpX7YMA2OlqKD8KKCaZCrmQA",authDomain:"bourbon-gestao.firebaseapp.com",projectId:"bourbon-gestao",storageBucket:"bourbon-gestao.firebasestorage.app",messagingSenderId:"424356195848",appId:"1:424356195848:web:43b8bdc7c51f5a99bfebbd"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let me=null,user=null;
const roles={admin:"Administrador",partner:"Sócio",cashier:"Caixa",kitchen:"Cozinha",gate:"Portaria",pending:"Aguardando liberação"};
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
async function ensureProfile(u,name=''){const ref=doc(db,'users',u.uid),s=await getDoc(ref);if(s.exists())return s.data();const all=await getDocs(collection(db,'users'));const data={name:name||u.email,email:u.email,role:all.empty?'admin':'pending',active:true,createdAt:serverTimestamp()};await setDoc(ref,data);return data}
async function audit(action,module,details={}){if(!user)return;await addDoc(collection(db,'audit_logs'),{action,module,details,userId:user.uid,userName:me?.name||user.email,createdAt:serverTimestamp()})}
onAuthStateChanged(auth,async u=>{if(!u){user=null;me=null;$('badge').textContent='Sistema integrado';show('login');return}user=u;me=await ensureProfile(u);$('badge').textContent=`${me.name} • ${roles[me.role]||me.role}`;await audit('login','autenticacao');startRealtime();show('dashboard')});
$('loginBtn').onclick=async()=>{try{$('msg').textContent='Entrando...';await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(e){$('msg').textContent='Confira e-mail e senha.'}};
$('showRegister').onclick=()=>$('registerCard').classList.toggle('hidden');
$('registerBtn').onclick=async()=>{try{const c=await createUserWithEmailAndPassword(auth,$('newEmail').value.trim(),$('newPassword').value);await ensureProfile(c.user,$('name').value.trim())}catch(e){alert(e.code==='auth/email-already-in-use'?'Este e-mail já possui cadastro.':'Erro: '+e.code)}};
$('forgotBtn').onclick=async()=>{const e=$('email').value.trim();if(!e)return alert('Digite o e-mail.');await sendPasswordResetEmail(auth,e);alert('E-mail enviado.')};
$('logoutBtn').onclick=async()=>{await audit('logout','autenticacao');await signOut(auth)};
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
$('saveEmployee').onclick=async()=>{if(!['admin','partner'].includes(me.role))return alert('Sem permissão.');const name=$('employeeName').value.trim();if(!name)return alert('Informe o nome.');await addDoc(collection(db,'employees'),{name,role:$('employeeRole').value.trim(),phone:$('employeePhone').value.trim(),dailyRate:Number($('employeeDaily').value)||0,active:true,createdAt:serverTimestamp(),createdByName:me.name});await audit('cadastrou funcionário','funcionarios',{name})};
$('saveBand').onclick=async()=>{if(!['admin','partner'].includes(me.role))return alert('Sem permissão.');const name=$('bandName').value.trim();if(!name)return alert('Informe o nome.');await addDoc(collection(db,'bands'),{name,contact:$('bandContact').value.trim(),phone:$('bandPhone').value.trim(),fee:Number($('bandFee').value)||0,active:true,createdAt:serverTimestamp(),createdByName:me.name});await audit('cadastrou banda','bandas',{name})};
window.delEmployee=async id=>{if(me.role!=='admin')return;await deleteDoc(doc(db,'employees',id));await audit('excluiu funcionário','funcionarios',{id})};window.delBand=async id=>{if(me.role!=='admin')return;await deleteDoc(doc(db,'bands',id));await audit('excluiu banda','bandas',{id})};
function renderEmployees(list){$('employeesList').innerHTML=list.length?list.map(x=>`<div class="item"><b>${x.name}</b><br><small>${x.role||'Função não informada'}</small><div class="row"><span>Telefone</span><b>${x.phone||'—'}</b></div><div class="row"><span>Diária</span><b>${money(x.dailyRate)}</b></div><button class="red" onclick="delEmployee('${x.id}')">Excluir</button></div>`).join(''):'<div class="item">Nenhum funcionário.</div>'}
function renderBands(list){$('bandsList').innerHTML=list.length?list.map(x=>`<div class="item"><b>${x.name}</b><br><small>${x.contact||'Responsável não informado'}</small><div class="row"><span>Telefone</span><b>${x.phone||'—'}</b></div><div class="row"><span>Valor</span><b>${money(x.fee)}</b></div><button class="red" onclick="delBand('${x.id}')">Excluir</button></div>`).join(''):'<div class="item">Nenhuma banda.</div>'}
async function renderUsers(){const s=await getDocs(collection(db,'users'));$('usersList').innerHTML=s.docs.map(d=>{const u=d.data();return`<div class="item"><b>${u.name}</b><br><small>${u.email} • ${roles[u.role]||u.role}</small></div>`}).join('')}async function renderAudit(){const s=await getDocs(query(collection(db,'audit_logs'),orderBy('createdAt','desc'),limit(50)));$('auditList').innerHTML=s.docs.map(d=>{const a=d.data();return`<div class="item"><b>${a.userName}</b> — ${a.action}<br><small>${a.module}</small></div>`}).join('')}
document.querySelector('[data-view="users"]').onclick=()=>{renderUsers();show('users')};document.querySelector('[data-view="audit"]').onclick=()=>{renderAudit();show('audit')};
function startRealtime(){onSnapshot(query(collection(db,'employees'),orderBy('createdAt','desc')),s=>{const l=s.docs.map(d=>({id:d.id,...d.data()}));$('statEmployees').textContent=l.length;renderEmployees(l)});onSnapshot(query(collection(db,'bands'),orderBy('createdAt','desc')),s=>{const l=s.docs.map(d=>({id:d.id,...d.data()}));$('statBands').textContent=l.length;renderBands(l)});onSnapshot(collection(db,'users'),s=>$('statUsers').textContent=s.size);onSnapshot(collection(db,'audit_logs'),s=>$('statLogins').textContent=s.docs.filter(d=>d.data().action==='login').length)}
